#  Lable Encoder

In [2]:
# jab koi order me data , (category data )ko  batana hota h tab use kare 
# low-0 ,medium-1, high-2
#high school , gradute, post g
#   order hai  - Label encoding use kare 
#   order nahi hai  - One Hot Encoder  ka use kare 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [12]:
df = pd.DataFrame({"Name":["Amana","OM","shivangi","Ajay","MAAN","OM"]})

In [13]:
df

       Name
0     Amana
1        OM
2  shivangi
3      Ajay
4      MAAN
5        OM

In [7]:
from sklearn.preprocessing import LabelEncoder

In [8]:
le = LabelEncoder()

In [14]:
le.fit_transform(df["Name"])

array([1, 3, 4, 0, 2, 3])

In [15]:
df["en_name"] = le.fit_transform(df["Name"])

In [16]:
df

       Name  en_name
0     Amana        1
1        OM        3
2  shivangi        4
3      Ajay        0
4      MAAN        2
5        OM        3

In [17]:
new_data = df
new_data.to_csv("Label_Encoder.csv",index=False)